import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/next";
import "./globals.scss";

const harmond = localFont({
  src: "./fonts/Harmond-SemBdItaCond.woff2",
  variable: "--font-harmond",
  display: "swap",
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${harmond.variable} ${archivo.variable}`}>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
